### ISSUE TITLE
Not working in linux (Ubuntu)

### ISSUE THREAD

**Issue by marcopiraccini** [steelbrain/denode#1]
Hi, 
Great idea :)
I'm trying it with Ubuntu. 
For some reason, id doesn't work. To make it work, I have to comment out the following lines: 

```
  // win.webContents.once('devtools-closed', function() {
  //   setImmediate(function() {
  //     win.close()
  //   })
  // })
```

...otherwise the devtools  starts and end immediately. But I didn’t figure out why...

**Comment by steelbrain** [comment]
It might be a bug in [`electron`](https://github.com/electron/electron). I'll try to repro on a Ubuntu VM soon
