### ISSUE TITLE
Filter node_modules from Sources list

### ISSUE THREAD

**Issue by bencooling** [steelbrain/denode#10]
I am finding denode a useful lightweight solution for setting breakpoints in my project files but it is a bit tedious to search through source code of not only my project dependencies but also denode itself under the Sources tab. 

Is it possible to filter out denode and project dependencies from Sources?

Thanks for a great application.

**Comment by steelbrain** [comment]
Hi @bencooling. DeNode uses chromium dev tools so everything that's possible in them is possible in it.
A quick look through the dev tools found me this,
<img src="https://cloud.githubusercontent.com/assets/4278113/15416090/70685ee4-1dfc-11e6-9e98-114324fcc847.png">
It shows what the keyboard shortcut is on both the background tip and the dropdown item
and when you press that keybinding, you can filter and open the particular file you want
<img src="https://cloud.githubusercontent.com/assets/4278113/15416101/8cacbb04-1dfc-11e6-9f83-9e3731d3d2e4.png">

**Comment by steelbrain** [comment]
Also here's a full cheatsheet http://anti-code.com/devtools-cheatsheet/
