### ISSUE TITLE
Error indexOf of undefined

### ISSUE THREAD

**Issue by knownasilya** [steelbrain/denode#11]
<img width="420" alt="screen shot 2016-06-08 at 9 57 23 am" src="https://cloud.githubusercontent.com/assets/34726/15896712/6f656268-2d5f-11e6-92c7-c3aa63597f1f.png">

Was just running `denode index.js` where `node index.js` worked.

Using denode 1.6.1

**Comment by steelbrain** [comment]
Thanks for the report, investigating

**Comment by steelbrain** [comment]
Fix published in 1.6.2
