### ISSUE TITLE
"Helper" tab name

### ISSUE THREAD

**Issue by knownasilya** [steelbrain/denode#13]
Not sure what needs to be tweaked to fix this (the second tab is `denode`):

<img width="572" alt="screen shot 2016-07-26 at 6 38 30 pm" src="https://cloud.githubusercontent.com/assets/34726/17157854/474d1b00-5360-11e6-9e73-1663c8d0c45f.png">

**Comment by steelbrain** [comment]
Yeah well this is actually a limitation coming from Electron, it has apps that execute most tasks (or maybe even the master of all browser windows?) named as Helper.
