### ISSUE TITLE
Can this be used with debugger?

### ISSUE THREAD

**Issue by razzius** [steelbrain/denode#22]
Say I have a module like so:

```js
// index.js
var x = 3
debugger
console.log(x)
```

Is it possible to use denode in such a way that it would start running the script and pause on the `debugger` breakpoint like in frontend js?

(generally I couldn't figure out how to interact with my modules - denode pops up and show the export of the main module but I couldn't figure out how to control execution)

**Comment by steelbrain** [comment]
YES! The `debugger` works perfectly with debugger

**Comment by razzius** [comment]
Hm running

`denode index.js`

does not pause for me:

![screen shot 2017-03-18 at 10 29 55 pm](https://cloud.githubusercontent.com/assets/2244895/24078423/8ee2476e-0c2a-11e7-9430-7860e7c26239.png)

**Comment by steelbrain** [comment]
That could actually be a race condition in the code, instead of doing `denode myscript.js`, try `denode` and then `require('./myscript')` in dev tools, this will make sure that the dev tools are loaded before the script is executed

I'll also try to fix this in denode

**Comment by razzius** [comment]
Yay it works to `require('./index')` ᕕ( ᐛ )ᕗ
