### ISSUE TITLE
[feature] denode start

### ISSUE THREAD

**Issue by knownasilya** [steelbrain/denode#4]
Would love to see `denode start` be a thing, kind of like `npm start` but it would just use the `main` property in the package.json.

This could also fix the issue where it's almost indistinguishable which app is being run, since all of the devtools windows say something like: 

![screen shot 2016-04-20 at 1 13 29 pm](https://cloud.githubusercontent.com/assets/34726/14683627/b42f4878-06f9-11e6-82a4-f058929ed479.png)

So the `name` property from the package.json and the file name from `main` property could be used together: `my-project: index.js`

**Comment by steelbrain** [comment]
If you want denode to use the `main` property of a package, you could just do `denode ./`

You are right about the title, it should be fixed, maybe by adding a virtual file system layer and then visiting the main file there instead of `file://`, should be pretty easy

**Comment by knownasilya** [comment]
Might be nice to document `denode .`.

**Comment by steelbrain** [comment]
I would be happy to accept a PR for this :)

**Comment by steelbrain** [comment]
It looks like this now, it scans ./package.json for a name and fallback to `DeNode`

<img width="225" alt="screen shot 2016-04-20 at 10 35 41 am" src="https://cloud.githubusercontent.com/assets/4278113/14684209/a97d05e8-06e3-11e6-9861-d520c774eb79.png">

**Comment by steelbrain** [comment]
Released in `v1.2.0`

**Comment by knownasilya** [comment]
Nice 👍
